In [2]:
import os
import numpy as np
import csv
import pandas as pd

In [3]:
pm = r"$\pm$"
print(pm)

$\pm$


In [4]:
pm = r"$\pm$"
main_path = "."
FILE_ENDING = ".csv"
APP = ""
# APP = ""
# FILE_ENDING = ".txt"
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet32']

# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif10rn34']
# datasets=['cif100rn34']
datasets=['imagenet']
# datasets=['cif10_rb']
# datasets=['imagenet32']
# datasets=['celebaHQ64']

# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'celebaHQ32', 'celebaHQ64','celebaHQ128', 'imagenet32', 'imagenet64','imagenet128', 'imagenet']
# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'imagenet']
# datasets=['cif10', 'cif100', 'cif10vgg', 'cif100vgg', 'imagenet' ]
# datasets=['cif10', 'cif100']
# datasets=['imagenet' ]

In [6]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 }
)

# columns = ["auc", "acc", "pre", "tpr", "f1", "fnr", "asr", "asrd"]
columns = ["asr", "auc", "f1", "acc", "pre", "tpr", "fnr", "asrd"]
selected_cols = ["0","asr", "auc", "fnr" , "asrd"]

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr  = []
    
    dataset_name = dataset + APP
    
    print("dataset_nameÖ ", dataset_name) 
    
    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset_name + FILE_ENDING)) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print("len(d_frame)", len(d_frame))
    print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
                                
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result, 1))
    
    str_var = np.around(result, 1).astype(str)
    print("result: ", result, type(result))
    # str_var = np.format_float_positional(np.around(result, 1), unique=False, precision=1)
    print(str_var)
    
    base = []
    # np.set_printoptions(formatter = {
    # 'float': lambda x: np.format_float_positional(x, unique=False, precision=2)
    #  }
    # )
    
    
    # base_final = np.chararray_like(np_arr[0])
    
    
    print("dddddddddddddddddddddddddddddddddddddddddddd")
    base = np_arr[0].astype(str)
    print("base: ", base)
    
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    
    df.insert(0, "0", d_frame[0].iloc[:,0], True)
    
    sel_df = df[selected_cols]
    print(df)
    
    sel_df.to_csv( "var_all/" + dataset_name + "_var.csv", index=True)
    sel_df.to_csv( dataset_name + "_var.csv", index=True)

dataset_nameÖ  imagenet
len(d_frame) 3
same shape True
[[0.0 0.2 0.1 0.2 0.4 0.0 0.0 0.0]
 [0.3 0.2 0.3 0.2 0.1 1.4 1.4 1.0]
 [0.0 0.2 0.0 0.3 1.9 1.0 1.0 1.0]
 [0.0 0.1 0.1 0.3 2.5 1.7 1.7 1.7]
 [0.0 0.0 0.6 0.4 0.1 2.2 2.2 2.2]
 [0.0 0.0 8.4 0.0 0.0 20.2 20.2 20.2]
 [0.0 0.0 4.1 0.0 0.0 10.2 10.2 10.2]
 [0.0 0.1 0.6 0.9 1.8 0.0 0.0 0.0]
 [0.3 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.5 0.8 1.4 1.8 0.0 0.0 0.0]
 [0.0 0.1 0.7 1.0 2.6 0.1 0.1 0.1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.2 4.1 1.2 1.3 8.2 8.2 8.2]
 [0.0 1.0 0.9 1.3 1.3 0.5 0.5 0.5]
 [0.0 0.0 0.0 0.0 0.2 0.2 0.2 0.2]
 [0.3 0.0 0.0 0.0 0.1 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 1.5 2.1 2.4 2.6 4.0 4.0 4.0]
 [0.0 2.2 1.8 1.9 1.7 2.3 2.3 2.3]
 [0.0 0.2 0.3 0.3 0.2 0.7 0.7 0.7]
 [0.3 0.0 0.1 0.1 0.1 0.3 0.3 0.2]
 [0.0 0.0 0.1 0.1 0.3 0.2 0.2 0.2]
 [0.0 0.0 1.0 1.0 1.1 1.0 1.0 1.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.7 0.7 0.8 1.1 3.0 3.0