In [1]:
import os
import numpy as np
import csv
import pandas as pd

In [2]:
pm = r"$\pm$"
print(pm)

$\pm$


In [3]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 })

In [6]:
pm = r"$\pm$"
main_path = "."
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10', 'cif100']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif100rn34']
# datasets=['cif10rn34', 'cif100rn34']

datasets=['imagenet32', 'imagenet64', 'cif10_rb', 'imagenet']

columns = ['auc', 'acc', 'pre', 'tpr', 'f1', 'fnr', 'asr', 'asrd']

runs = 3

for dataset in datasets:
    print(dataset)
    d_frame = []
    np_arr = []

    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_dfcw_" + str(idx_run), dataset+".txt")) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print( "len(d_frame)", len(d_frame) )
    print( "same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape )

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
                                
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result,1))
    
    str_var = np.around(result,1).astype(str)
    base = np_arr[0].astype(str)
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    df.insert(0, "0", d_frame[0].iloc[:,0], True)

    df.to_csv( "var_dfcw/" + dataset + "_var.csv", index=True)

imagenet32
len(d_frame) 3
same shape True
[[0.0 0.0 0.1 3.9 1.4 3.9 0.0 3.9]
 [0.0 0.0 0.0 9.4 2.5 9.4 0.0 9.4]
 [0.1 0.0 0.0 0.8 0.2 0.8 0.0 0.8]
 [0.1 1.1 1.1 0.5 0.5 0.5 0.0 0.5]
 [1.0 1.2 1.6 1.4 1.0 1.4 0.0 1.4]
 [1.3 0.2 0.4 2.0 0.3 2.0 0.0 2.0]
 [0.3 0.7 0.5 7.2 2.8 7.2 0.0 7.2]
 [0.2 0.6 0.8 6.1 1.4 6.1 0.0 6.1]]
imagenet64
len(d_frame) 3
same shape True
[[0.0 0.0 0.0 8.5 2.7 8.5 0.0 8.5]
 [0.0 0.0 0.0 10.7 4.2 10.7 0.0 10.7]
 [0.2 0.2 0.2 7.6 2.5 7.6 0.0 7.6]
 [1.3 0.7 0.7 14.1 4.7 14.1 0.0 14.1]
 [0.0 0.3 0.4 0.7 0.4 0.7 0.0 0.7]
 [0.3 0.0 0.4 7.2 1.4 7.2 0.0 7.2]
 [0.1 0.0 0.2 6.1 1.2 6.1 0.0 6.1]
 [0.7 1.3 1.6 3.7 1.6 3.7 0.0 3.7]]
cif10_rb
len(d_frame) 3
same shape True
[[1.3 1.9 1.7 20.0 8.9 20.0 0.0 20.0]
 [0.5 0.9 0.8 8.7 4.4 8.7 0.0 8.7]
 [0.5 0.8 3.5 7.6 1.0 7.6 0.0 7.6]
 [0.2 0.1 0.3 14.9 1.3 14.9 0.0 14.9]
 [1.6 2.0 2.4 5.6 3.2 5.6 0.0 5.6]
 [2.3 1.7 1.2 7.0 3.7 7.0 0.0 7.0]
 [0.6 1.5 2.0 0.9 1.1 0.9 0.0 0.9]
 [0.1 0.0 0.1 1.1 0.2 1.1 0.0 1.1]]
imagenet
len(d_frame)