In [1]:
import os
import numpy as np
import csv
import pandas as pd

In [2]:
pm = r"$\pm$"
print(pm)

$\pm$


In [3]:
pm = r"$\pm$"
main_path = "."
FILE_ENDING = ".csv"
# APP = "_LID"
APP = "_LIDFeatures"

# APP = ""
# FILE_ENDING = ".txt"
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet32']

# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif10rn34']
# datasets=['cif100rn34']
# datasets=['imagenet']
# datasets=['cif10_rb']
# datasets=['imagenet32']
# datasets=['celebaHQ64']

# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'celebaHQ32', 'celebaHQ64','celebaHQ128', 'imagenet32', 'imagenet64','imagenet128', 'imagenet']
# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'imagenet']
datasets=['cif10', 'cif100', 'cif10vgg', 'cif100vgg', 'imagenet']
# datasets=['cif10', 'cif100']
# datasets=['imagenet' ]

In [4]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 }
)

# columns = ["auc", "acc", "pre", "tpr", "f1", "fnr", "asr", "asrd"]
columns = ["asr", "auc", "f1", "acc", "pre", "tpr", "fnr", "asrd"]
selected_cols = ["0","asr", "auc", "fnr" , "asrd"]

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr  = []
    
    dataset_name = dataset + APP
    
    print("dataset_name ", dataset_name) 
    
    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset_name + FILE_ENDING)) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print("len(d_frame)", len(d_frame))
    print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])
    res_mean = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
            mean = np.mean( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))                  
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result, 1))
    
    str_var = np.around(result, 1).astype(str)
    print("result: ", result, type(result))
    # str_var = np.format_float_positional(np.around(result, 1), unique=False, precision=1)
    print(str_var)
    
    base = []
    # np.set_printoptions(formatter = {
    # 'float': lambda x: np.format_float_positional(x, unique=False, precision=2)
    #  }
    # )
    
    
    # base_final = np.chararray_like(np_arr[0])
    
    
    print("dddddddddddddddddddddddddddddddddddddddddddd")
    base = np_arr[0].astype(str)
    print("base: ", base)
    
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    
    df.insert(0, "0", d_frame[0].iloc[:,0], True)
    
    sel_df = df[selected_cols]
    print(df)
    
    sel_df.to_csv( "var_all/" + dataset_name + "_var.csv", index=True)
    sel_df.to_csv( dataset_name + "_var.csv", index=True)

dataset_name  cif10_LIDFeatures
len(d_frame) 3
same shape True
[[0.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.1 0.0 0.0 0.1 0.0 0.0]
 [0.0 0.0 0.0 0.1 0.0 0.0 0.1 0.0 0.0]
 [0.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]]
result:  [[0.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.1 0.0 0.0 0.1 0.0 0.0]
 [0.0 0.0 0.0 0.1 0.0 0.0 0.1 0.0 0.0]
 [0.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 

ValueError: Shape of passed values is (12, 9), indices imply (12, 8)

In [7]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 }
)

# columns = ["auc", "acc", "pre", "tpr", "f1", "fnr", "asr", "asrd"]
columns = [ 'asr', 'auc',   'f1', 'acc', 'pre', 'tpr', 'tnr', 'fnr', 'asrd']
# columns = ["asr", "auc", "f1", "acc", "pre", "tpr", "fnr", "asrd"]
selected_cols = ["0",  'asr', 'auc',   'f1', 'acc', 'pre', 'tpr', 'tnr', 'fnr', 'asrd']
# selected_cols = ["0", "auc", "f1"]

final_df = []

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr  = []
    
    dataset_name = dataset + APP
    
    # print("dataset_name ", dataset_name) 
    
    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset_name + FILE_ENDING)) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    # print("len(d_frame)", len(d_frame))
    # print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])
    res_mean = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
            mean = np.mean( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))                  
            if variance > 500:
                # print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
            res_mean[row, col] = mean
    # print(np.around(result, 1))
    
    str_var = np.around(result, 1).astype(str)
    str_mean = np.around(res_mean, 1).astype(str)
    # print("result: ", result, type(result))
    # str_var = np.format_float_positional(np.around(result, 1), unique=False, precision=1)
    # print(str_var)
    
    base = []
    # np.set_printoptions(formatter = {
    # 'float': lambda x: np.format_float_positional(x, unique=False, precision=2)
    #  }
    # )
    
    
    # base_final = np.chararray_like(np_arr[0])
    
    
    # print("dddddddddddddddddddddddddddddddddddddddddddd")
    # base = np_arr[0].astype(str)
    base = str_mean.astype(str)
    # print("base: ", base)
    
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    
    df.insert(0, "0", d_frame[0].iloc[:,0], True)
    
    sel_df = df[selected_cols]
    # print(df)
    final_df.append(sel_df)


all_df = pd.concat(final_df)

# all_df.to_csv( "var_all/" + ''.join(datasets) + APP + "_var.csv", index=True)
# sel_df.to_csv( "var_all/" + dataset_name + "_var.csv", index=True)
# sel_df.to_csv( dataset_name + "_var.csv", index=True)

In [8]:
all_df

0            asr  \
0   ./data/detection/run_1/cif10/wrn_28_10_10/fgsm...   48.0$\pm$0.2   
1   ./data/detection/run_1/cif10/wrn_28_10_10/bim/...  100.0$\pm$0.0   
2   ./data/detection/run_1/cif10/wrn_28_10_10/std/...  100.0$\pm$0.0   
3   ./data/detection/run_1/cif10/wrn_28_10_10/pgd/...  100.0$\pm$0.0   
4   ./data/detection/run_1/cif10/wrn_28_10_10/df/L...  100.0$\pm$0.0   
5   ./data/detection/run_1/cif10/wrn_28_10_10/cw/L...  100.0$\pm$0.0   
6   ./data/detection/run_1/cif10/wrn_28_10_10/fgsm...   48.0$\pm$0.2   
7   ./data/detection/run_1/cif10/wrn_28_10_10/bim/...  100.0$\pm$0.0   
8   ./data/detection/run_1/cif10/wrn_28_10_10/std/...  100.0$\pm$0.0   
9   ./data/detection/run_1/cif10/wrn_28_10_10/pgd/...  100.0$\pm$0.0   
10  ./data/detection/run_1/cif10/wrn_28_10_10/df/L...  100.0$\pm$0.0   
11  ./data/detection/run_1/cif10/wrn_28_10_10/cw/L...  100.0$\pm$0.0   
0   ./data/detection/run_1/cif100/wrn_28_10_100/fg...   84.5$\pm$0.0   
1   ./data/detection/run_1/cif100/wrn_28_10_100/bi...   99.9$\pm$0.0   
2   ./data/detection/run_1/cif100/wrn_28_10_100/st...  100.0$\pm$0.0   
3   ./data/detection/run_1/cif100/wrn_28_10_100/pg...   99.9$\pm$0.0   
4   ./data/detection/run_1/cif100/wrn_28_10_100/df...  100.0$\pm$0.0   
5   ./data/detection/run_1/cif100/wrn_28_10_100/cw...  100.0$\pm$0.0   
6   ./data/detection/run_1/cif100/wrn_28_10_100/fg...   84.5$\pm$0.0   
7   ./data/detection/run_1/cif100/wrn_28_10_100/bi...   99.9$\pm$0.0   
8   ./data/detection/run_1/cif100/wrn_28_10_100/st...  100.0$\pm$0.0   
9   ./data/detection/run_1/cif100/wrn_28_10_100/pg...   99.9$\pm$0.0   
10  ./data/detection/run_1/cif100/wrn_28_10_100/df...  100.0$\pm$0.0   
11  ./data/detection/run_1/cif100/wrn_28_10_100/cw...  100.0$\pm$0.0   
0   ./data/detection/run_1/cif10vgg/vgg_16_0_10/fg...   95.8$\pm$0.1   
1   ./data/detection/run_1/cif10vgg/vgg_16_0_10/bi...  100.0$\pm$0.0   
2   ./data/detection/run_1/cif10vgg/vgg_16_0_10/st...  100.0$\pm$0.0   
3   ./data/detection/run_1/cif10vgg/vgg_16_0_10/pg...  100.0$\pm$0.0   
4   ./data/detection/run_1/cif10vgg/vgg_16_0_10/df...  100.0$\pm$0.0   
5   ./data/detection/run_1/cif10vgg/vgg_16_0_10/cw...  100.0$\pm$0.0   
6   ./data/detection/run_1/cif10vgg/vgg_16_0_10/fg...   95.8$\pm$0.1   
7   ./data/detection/run_1/cif10vgg/vgg_16_0_10/bi...  100.0$\pm$0.0   
8   ./data/detection/run_1/cif10vgg/vgg_16_0_10/st...  100.0$\pm$0.0   
9   ./data/detection/run_1/cif10vgg/vgg_16_0_10/pg...  100.0$\pm$0.0   
10  ./data/detection/run_1/cif10vgg/vgg_16_0_10/df...  100.0$\pm$0.0   
11  ./data/detection/run_1/cif10vgg/vgg_16_0_10/cw...  100.0$\pm$0.0   
0   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   72.1$\pm$0.0   
1   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   98.3$\pm$0.0   
2   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
3   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   98.2$\pm$0.0   
4   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
5   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
6   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   72.1$\pm$0.0   
7   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   98.3$\pm$0.0   
8   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
9   ./data/detection/run_1/cif100vgg/vgg_16_0_100/...   98.2$\pm$0.0   
10  ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
11  ./data/detection/run_1/cif100vgg/vgg_16_0_100/...  100.0$\pm$0.0   
0   ./data/detection/run_1/imagenet/wrn_50_2/fgsm/...   86.4$\pm$0.3   
1   ./data/detection/run_1/imagenet/wrn_50_2/bim/L...  100.0$\pm$0.0   
2   ./data/detection/run_1/imagenet/wrn_50_2/std/8...  100.0$\pm$0.0   
3   ./data/detection/run_1/imagenet/wrn_50_2/pgd/L...  100.0$\pm$0.0   
4   ./data/detection/run_1/imagenet/wrn_50_2/df/LI...  100.0$\pm$0.0   
5   ./data/detection/run_1/imagenet/wrn_50_2/cw/LI...  100.0$\pm$0.0   
6   ./data/detection/run_1/imagenet/wrn_50_2/fgsm/...   86.4$\pm$0.3   
7   ./data/detection