In [1]:
import numpy as np

In [3]:



np.ones((30,15))



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [38]:
cif10_1 = np.array(
 [
[95.08  ,  97.34  ,  97.72  ,  2.33  ,    0.00  ,   2.22  ,   0.00  ,  99.01  ,  97.88  ,   0.00  ,   0.00  ,   0.00  ,   0.00],
[99.37  ,  92.93  ,  95.54  ,  8.00  ,    0.00  ,   7.95  ,   0.00  ,  97.65  ,  96.44  ,   3.00  ,   0.67  ,   2.98  ,   0.67],
[99.27  ,  91.79  ,  95.24  ,  8.67  ,    0.00  ,   8.61  ,   0.00  ,  96.70  ,  95.85  ,   2.33  ,   0.00  ,   2.31  ,   0.00],
[100.0  ,  91.78  ,  96.31  ,  7.00  ,    0.00  ,   7.00  ,   0.00  ,  98.00  ,  96.76  ,   2.00  ,   0.33  ,   2.00  ,   0.33],
[100.0  ,  48.31  ,  49.47  ,  54.67  ,  53.33  ,  54.67  ,  53.33  ,  54.42  ,  52.30  ,  45.67  ,  47.00  ,  45.67  ,  47.00],
[100.0  ,  48.07  ,  53.75  ,  54.33  ,  42.67  ,  54.33  ,  42.67  ,  53.29  ,  54.52  ,  47.33  ,  40.67  ,  47.33  ,  40.67],
[ 100    ,  50.17  ,  64.20  ,  49.67  ,  10.33   , 49.67  ,  10.33  ,  47.92  ,  47.29   , 54.00  ,  55.00  ,  54.00 ,   55.00 ]
 ]
)

cif10_2 = np.array(
 [
[  95.82,  98.18, 98.36 ,  1.33 ,  0.00 ,  1.27 ,  0.00 , 99.83 , 98.04 ,  0.00 ,  0.00 ,  0.00 ,  0.00],
[  99.37,  91.37, 96.15 , 10.00 ,  0.00 ,  9.94 ,  0.00 , 97.01 , 95.19 ,  2.67 ,  1.00 ,  2.65 ,  0.99],
[  99.22,  91.27, 94.79 ,  7.67 ,  0.00 ,  7.61 ,  0.00 , 98.18 , 94.89 ,  1.33 ,  1.00 ,  1.32 ,  0.99],
[  100.0,  92.95, 94.62 ,  7.67 ,  0.33 ,  7.67 ,  0.33 , 99.17 , 96.62 ,  1.00 ,  0.00 ,  1.00 ,  0.00],
[  100.0,  48.96, 51.89 , 53.00 , 47.33 , 53.00 , 47.33 , 52.42 , 51.97 , 47.67 , 47.33 , 47.67 , 47.33],
[  100.0,  48.97, 56.18 , 52.33 , 36.33 , 52.33 , 36.33 , 54.08 , 54.29 , 43.67 , 41.00 , 43.67 , 41.00],

 ]
)

cif10_3 = np.array(
 [
[  95.77 , 98.84 , 98.68 ,  0.67 ,  0.00 ,  0.64 ,  0.00 , 99.83 , 98.36 ,  0.00 ,  0.33 ,  0.00 ,  0.32],
[  99.56 , 93.38 , 95.09 ,  6.00 ,  0.00 ,  5.97 ,  0.00 , 97.35 , 96.61 ,  2.00 ,  0.33 ,  1.99 ,  0.33],
[  99.51 , 92.59 , 95.09 ,  8.33 ,  0.00 ,  8.29 ,  0.00 , 96.85 , 95.37 ,  2.67 ,  0.33 ,  2.66 ,  0.33],
[  100   , 94.39 , 94.19 ,  4.67 ,  0.00 ,  4.67 ,  0.00 , 98.01 , 96.93 ,  1.67 ,  0.00 ,  1.67 ,  0.00],
[  100   , 46.85 , 47.00 , 56.67 , 55.67 , 56.67 , 55.67 , 48.94 , 52.20 , 53.67 , 46.67 , 53.67 , 46.67],
[  100   , 46.38 , 50.66 , 57.33 , 48.67 , 57.33 , 48.67 , 47.38 , 53.52 , 56.33 , 43.00 , 56.33 , 43.00],

 ]
)

for row in range(i):
    for col in range(j):
        variance = np.var( np.array([cif10_1[row, col], cif10_2[row, col], cif10_3[row, col] ]))
        
        
        result[row, col] = variance
        
print(np.around(result,1))

[[ 0.1  0.4  0.2  0.5  0.   0.4  0.   0.1  0.   0.   0.   0.   0. ]
 [ 0.   0.7  0.2  2.7  0.   2.6  0.   0.1  0.4  0.2  0.1  0.2  0.1]
 [ 0.   0.3  0.   0.2  0.   0.2  0.   0.4  0.2  0.3  0.2  0.3  0.2]
 [ 0.   1.1  0.8  1.7  0.   1.7  0.   0.3  0.   0.2  0.   0.2  0. ]
 [ 0.   0.8  4.   2.3 12.3  2.3 12.3  5.1  0.  11.6  0.1 11.6  0.1]
 [ 0.   1.2  5.1  4.2 25.4  4.2 25.4  8.9  0.2 28.3  1.1 28.3  1.1]]


In [6]:
cif100_1 = np.array(
 [
[ 99.95  ,  94.58  ,  97.72  ,   7.00  ,   0.00   ,  7.00  ,   0.00  ,  99.34  ,  98.85   ,  0.33  ,   0.00  ,   0.33 ,    0.00 ],
[ 99.95  ,  87.39  ,  95.39  ,  15.67  ,   0.00   , 15.66  ,   0.00  ,  97.00  ,  98.50   ,  3.00  ,   1.33  ,   3.00 ,    1.33 ],
[ 99.95  ,  86.97  ,  95.24  ,  14.33  ,   0.00   , 14.32  ,   0.00  ,  96.83  ,  98.68   ,  3.33  ,   0.00  ,   3.33 ,    0.00 ],
[ 100    ,  92.57  ,  96.76  ,   8.67  ,   0.33   ,  8.67  ,   0.33  ,  97.35  ,  97.72   ,  2.00  ,   0.00  ,   2.00 ,    0.00 ],
[ 100    ,  50.17  ,  51.84  ,  49.67  ,  46.00   , 49.67  ,  46.00  ,  50.33  ,  48.00   , 49.33  ,  54.00  ,  49.33 ,   54.00 ],
[ 100    ,  50.17  ,  64.20  ,  49.67  ,  10.33   , 49.67  ,  10.33  ,  47.92  ,  47.29   , 54.00  ,  55.00  ,  54.00 ,   55.00 ]
 ]
)

cif100_2 = np.array(
 [
[99.95 ,   93.78,    97.88  ,   7.00  ,   0.00 ,    7.00  ,   0.00  ,  98.84 ,   97.88 ,    0.33 ,    0.00 ,    0.33 ,    0.00 ],
[  100 ,   89.48,    94.64  ,  10.67  ,   0.00 ,   10.67  ,   0.00  ,  95.78 ,   97.86 ,    5.33 ,    1.00 ,    5.33 ,    1.00 ],
[  100 ,   88.15,    95.09  ,  12.00  ,   0.00 ,   12.00  ,   0.00  ,  96.32 ,   97.86 ,    4.00 ,    1.00 ,    4.00 ,    1.00 ],
[  100 ,   89.82,    95.39  ,  10.33  ,   0.00 ,   10.33  ,   0.00  ,  97.19 ,   97.24 ,    2.00 ,    0.00 ,    2.00 ,    0.00 ],
[  100 ,   47.55,    49.32  ,  54.67  ,  51.33 ,   54.67  ,  51.33  ,  49.49 ,   52.55 ,   51.00 ,   45.00 ,   51.00 ,   45.00 ],
[  100 ,   48.10,    63.77  ,  53.67  ,  12.00 ,   53.67  ,  12.00  ,  49.92 ,   49.15 ,   50.33 ,   51.67 ,   50.33 ,   51.67 ],
 ]
)

cif100_3 = np.array(
 [
[99.76 ,   94.65,    97.56  ,   5.67  ,   0.00 ,    5.66  ,   0.00  ,  99.67 ,   98.68 ,    0.00 ,    0.00 ,    0.00 ,    0.00 ],
[99.85 ,   86.81,    94.94  ,  13.33  ,   0.00 ,   13.31  ,   0.00  ,  96.63 ,   97.87 ,    4.33 ,    0.33 ,    4.32 ,    0.33 ],
[99.85 ,   86.34,    94.32  ,  14.67  ,   0.33 ,   14.65  ,   0.33  ,  95.62 ,   97.70 ,    5.33 ,    0.67 ,    5.32 ,    0.67 ],
[100   ,   91.72,    94.64  ,   7.67  ,   0.00 ,    7.67  ,   0.00  ,  97.16 ,   96.61 ,    3.00 ,    0.33 ,    3.00 ,    0.33 ],
[100   ,   47.92,    48.81  ,  54.00  ,  52.33 ,   54.00  ,  52.33  ,  51.92 ,   50.74 ,   46.00 ,   48.33 ,   46.00 ,   48.33 ],
[100   ,   48.28,    64.29  ,  53.33  ,  10.00 ,   53.33  ,  10.00  ,  51.06 ,   50.74 ,   48.00 ,   48.67 ,   48.00 ,   48.67 ],
 ]
)

In [7]:
cif100_1.shape

(6, 13)

In [23]:
result = np.zeros_like(cif100_1, dtype=np.float64)

In [24]:
i = cif100_1.shape[0]
j = cif100_1.shape[1]

In [30]:
result.shape

(6, 13)

In [31]:
for row in range(i):
    for col in range(j):
        variance = np.var( np.array([cif100_1[row, col], cif100_2[row, col], cif100_3[row, col] ]))
        
        
        result[row, col] = variance
        
print(np.around(result,2))

In [36]:
print(np.around(result,2))

[[1.00e-02 1.60e-01 2.00e-02 3.90e-01 0.00e+00 4.00e-01 0.00e+00 1.20e-01
  1.80e-01 2.00e-02 0.00e+00 2.00e-02 0.00e+00]
 [0.00e+00 1.31e+00 1.00e-01 4.17e+00 0.00e+00 4.15e+00 0.00e+00 2.60e-01
  9.00e-02 9.10e-01 1.70e-01 9.10e-01 1.70e-01]
 [0.00e+00 5.60e-01 1.60e-01 1.41e+00 2.00e-02 1.39e+00 2.00e-02 2.50e-01
  1.80e-01 6.90e-01 1.70e-01 6.80e-01 1.70e-01]
 [0.00e+00 1.32e+00 7.70e-01 1.20e+00 2.00e-02 1.20e+00 2.00e-02 1.00e-02
  2.10e-01 2.20e-01 2.00e-02 2.20e-01 2.00e-02]
 [0.00e+00 1.34e+00 1.75e+00 4.91e+00 7.72e+00 4.91e+00 7.72e+00 1.02e+00
  3.50e+00 4.32e+00 1.38e+01 4.32e+00 1.38e+01]
 [0.00e+00 8.80e-01 5.00e-02 3.28e+00 7.70e-01 3.28e+00 7.70e-01 1.68e+00
  1.99e+00 6.10e+00 6.68e+00 6.10e+00 6.68e+00]]
