In [9]:
import os
import numpy as np
import csv
import pandas as pd

In [10]:
pm = r"$\pm$"
print(pm)

$\pm$


In [11]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 })

In [13]:
pm = r"$\pm$"
main_path = "."
FILE_ENDING = ".csv"
# FILE_ENDING = ".txt"
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10', 'cif100']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif10rn34']
# datasets=['cif100rn34']
# datasets=['imagenet']
datasets=['cif10_rb']

columns = ['auc', 'acc', 'pre', 'tpr', 'f1', 'fnr', 'asr', 'asrd']

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr = []

    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset + FILE_ENDING)) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print("len(d_frame)", len(d_frame))
    print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
                                
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result,1))
    
    str_var = np.around(result,1).astype(str)
    base = np_arr[0].astype(str)
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    df.insert(0, "0", d_frame[0].iloc[:,0], True)
    
    df.to_csv( "var_all/" + dataset + "_var.csv", index=True)
    df.to_csv( dataset + "_var.csv", index=True)

len(d_frame) 3
same shape True
[[0.8 1.1 3.5 0.1 0.9 0.1 0.0 0.1]
 [0.4 1.1 3.0 3.3 1.0 3.3 0.1 1.5]
 [0.8 0.6 0.6 0.5 0.6 0.5 0.0 0.3]
 [0.4 1.9 1.1 3.4 2.1 3.4 0.0 1.9]
 [0.3 2.1 5.4 0.2 1.4 0.2 0.0 0.0]
 [1.0 0.7 0.9 4.2 1.8 4.2 0.0 4.2]
 [0.6 0.5 1.0 2.1 0.2 2.1 0.0 2.1]
 [0.1 1.3 4.1 0.1 1.0 0.1 0.0 0.1]
 [0.1 1.2 2.8 0.0 0.9 0.0 0.1 0.0]
 [0.5 3.2 6.9 0.0 2.2 0.0 0.0 0.0]
 [0.6 3.0 6.5 0.0 2.3 0.0 0.0 0.0]
 [0.0 0.2 0.5 0.1 0.2 0.1 0.0 0.0]
 [0.8 1.3 4.6 9.0 2.5 9.0 0.0 9.0]
 [0.1 0.1 0.0 3.1 0.8 3.1 0.0 3.1]
 [2.5 2.7 4.5 1.6 2.4 1.6 0.0 1.6]
 [0.5 0.4 2.5 14.7 1.5 14.7 0.1 6.8]
 [0.4 0.6 1.3 0.5 0.1 0.5 0.0 0.3]
 [0.9 1.4 2.2 0.3 0.8 0.3 0.0 0.1]
 [0.0 3.0 3.5 4.3 3.7 4.3 0.0 0.3]
 [0.2 0.4 0.2 5.7 1.1 5.7 0.0 5.7]
 [0.3 0.5 0.4 3.1 0.8 3.1 0.0 3.1]
 [9.7 15.6 21.1 8.0 13.8 8.0 0.0 8.0]
 [0.2 1.1 0.8 12.0 4.0 12.0 0.1 5.8]
 [0.0 0.1 0.1 0.5 0.1 0.5 0.0 0.4]
 [0.3 0.0 0.2 6.7 1.2 6.7 0.0 3.8]
 [6.0 4.1 4.6 6.4 4.7 6.4 0.0 0.5]
 [0.1 0.0 0.2 4.3 0.2 4.3 0.0 4.3]
 [0.6 0.7 0.4 2.4