In [1]:
import os
import numpy as np
import csv
import pandas as pd

In [2]:
pm = r"$\pm$"
print(pm)

$\pm$


In [3]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 }
)

In [4]:
pm = r"$\pm$"
main_path = "."
FILE_ENDING = ".csv"
APP = "_LID"
# APP = ""
# FILE_ENDING = ".txt"
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10', 'cif100']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif10rn34']
# datasets=['cif100rn34']
# datasets=['imagenet']
# datasets=['cif10_rb']

# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'celebaHQ32', 'celebaHQ64','celebaHQ128', 'imagenet32', 'imagenet64','imagenet128', 'imagenet']
# datasets=['cif10', 'cif100', 'cif10vgg', 'cif10rn34', 'cif100rn34', 'cif10_rb' , 'cif100vgg', 'imagenet']
datasets=['cif10', 'cif100', 'cif10vgg', 'cif100vgg', 'imagenet' ]
datasets=['imagenet' ]

In [5]:
columns = ['auc', 'acc', 'pre', 'tpr', 'f1', 'fnr', 'asr', 'asrd']

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr  = []
    
    dataset_name = dataset + APP
    
    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset_name + FILE_ENDING)) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print("len(d_frame)", len(d_frame))
    print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([ np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
                                
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result, 1))
    
    str_var = np.around(result, 1).astype(str)
    base = np_arr[0].astype(str)
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    df.insert(0, "0", d_frame[0].iloc[:,0], True)
    
    df.to_csv( "var_all/" + dataset_name + "_var.csv", index=True)
    df.to_csv( dataset_name + "_var.csv", index=True)

len(d_frame) 3
same shape True
[[9.1 7.7 7.7 28.8 16.8 28.8 0.0 28.8]
 [0.9 1.4 1.3 26.6 4.4 26.6 0.3 21.5]
 [0.3 0.7 4.3 3.1 0.6 3.1 0.0 3.1]
 [0.0 0.0 3.3 5.4 0.1 5.4 0.0 5.4]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [3.0 10.0 7.6 3.8 5.9 3.8 0.0 3.8]
 [7.4 4.0 3.6 0.2 0.9 0.2 0.0 0.2]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.3 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]]
