In [1]:
import os
import numpy as np
import csv
import pandas as pd

In [2]:
pm = r"$\pm$"
print(pm)

$\pm$


In [3]:
np.set_printoptions(formatter = {
    'float': lambda x: "{0:0.1f}".format(x)
 })

In [5]:
pm = r"$\pm$"
main_path = "."
# datasets=['cif10vgg', 'cif100vgg']
# datasets=['cif10', 'cif100']
# datasets=['imagenet32', 'imagenet64','imagenet128']
# datasets=['imagenet128']

# datasets=['celebaHQ32', 'celebaHQ64','celebaHQ128']
# datasets=['celebaHQ32']
# datasets=['cif10rn34']
# datasets=['cif100rn34']
# datasets=['imagenet']
datasets=['cif10_rb']

columns = ['auc', 'acc', 'pre', 'tpr', 'f1', 'fnr', 'asr', 'asrd']

runs = 3

for dataset in datasets:
    d_frame = []
    np_arr = []

    for idx_run in range(1, runs+1):
        d_frame.append( pd.read_csv(os.path.join(main_path, "run_" + str(idx_run), dataset+".txt")) )
        arr1 = d_frame[idx_run - 1].to_numpy()
        np_arr.append(np.delete(arr1, [0], 1).astype('float32'))

    print("len(d_frame)", len(d_frame))
    print("same shape", np_arr[0].shape == np_arr[1].shape == np_arr[2].shape)

    i, j = np_arr[0].shape
    result = np.zeros_like(np_arr[0])

    for row in range(i):
        for col in range(j):
            variance = np.var( np.array([np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col] ]))
                                
            if variance > 500:
                print(np_arr[0][row, col], np_arr[1][row, col], np_arr[2][row, col])
                print("varrrrrrrrrrrrrr", variance)
            result[row, col] = variance
    print(np.around(result,1))
    
    str_var = np.around(result,1).astype(str)
    base = np_arr[0].astype(str)
    
    for row in range(i):
        for col in range(j):
            base[row,col] = base[row,col] + pm + str_var[row,col]
    
    df = pd.DataFrame(base, columns=columns)
    df.insert(0, "0", d_frame[0].iloc[:,0], True)

    df.to_csv( dataset + "_var.csv", index=True)

len(d_frame) 3
same shape True
[[0.5 0.8 4.0 4.0 0.6 4.0 0.1 1.8]
 [1.0 1.5 0.1 7.6 2.1 7.6 0.0 4.9]
 [0.7 2.1 1.6 3.1 2.2 3.1 0.0 1.7]
 [0.3 1.6 3.6 0.0 1.1 0.0 0.0 0.0]
 [1.0 0.7 1.3 8.3 2.7 8.3 0.0 8.3]
 [0.5 0.5 0.9 1.9 0.2 1.9 0.0 1.9]
 [0.2 1.2 2.8 0.0 0.9 0.0 0.1 0.0]
 [0.4 2.7 5.9 0.0 1.8 0.0 0.0 0.0]
 [0.5 1.6 3.0 0.1 1.2 0.1 0.0 0.0]
 [0.1 0.1 0.4 0.1 0.1 0.1 0.0 0.0]
 [1.0 1.8 3.7 15.4 5.0 15.4 0.0 15.4]
 [1.4 2.0 1.5 7.6 4.4 7.6 0.0 7.6]
 [0.3 2.9 0.4 10.7 3.7 10.7 0.1 4.9]
 [0.6 0.8 1.1 14.5 2.0 14.5 0.0 9.3]
 [1.9 0.6 3.4 2.1 0.4 2.1 0.0 1.2]
 [1.3 3.2 4.9 2.1 3.2 2.1 0.0 0.2]
 [0.9 0.7 0.1 6.4 2.3 6.4 0.0 6.4]
 [0.5 0.8 1.6 0.5 0.4 0.5 0.0 0.5]
 [0.3 0.1 0.0 1.3 0.2 1.3 0.1 0.6]
 [4.2 4.6 6.8 13.7 4.1 13.7 0.0 8.8]
 [1.0 0.2 1.7 8.9 0.6 8.9 0.0 5.0]
 [1.1 0.7 2.1 3.3 0.5 3.3 0.0 0.2]
 [0.5 0.5 0.8 5.3 1.5 5.3 0.0 5.3]
 [1.5 0.0 0.1 3.3 0.7 3.3 0.0 3.3]]
